# fileName: api_config.yml

host: http://localhost:8080

get_user_msg:
  name: 获取用户个人信息
  method: Get
  url: /api/user/me
  headers:
    Authorization: Basic
  expected:
    success: true

login_code:
  name: 【登录】获取手机验证码
  method: Get
  url: /api/user/code?phone=13119822252
  headers:
    Content-Type: application/json
  expected:
    success: true


get_blog:
  name: 【探店】获取一篇探店笔记
  method: Get
  url: /api/blog/4
  headers:
    Content-Type: application/json
  expected:
    success: true












login:
  name: 【登录】手机号码登录
  method: Post
  url: /v1/login/
  data:
    phone_country: 86
    phone_number: 1210000000
    password: 123456
    device_id: XXX
    device_name: Iphone8plus
    device_pubkey: XXX
  headers:
    Content-Type: application/x-www-form-urlencoded
    Authorization: Basic XXX

asset_main:
  name: 【资产】用户资产列表页
  method: Get
  url: /v2/main/
  headers:
    Authorization: Bearer
    app-version: 4.8.0
    device-id: XXX
  expected:
    success: true

lend:
  name: 发送请求
  method: Post
  url: /v1/lend/
  data:
    payment_password: 123456
    amount: 100
    pledge_source: 1
  headers:
    Content-Type: application/x-www-form-urlencoded
    Authorization: Bearer
    device-id: XXX
    app-version: 4.8.0